SHOW DATABASES; 

DROP DATABASE IF EXISTS BONSAUVEUR;

create database BONSAUVEUR;

USE BONSAUVEUR;

DROP TABLE IF exists OUTILS;

DROP TABLE IF exists UTILISATEURS;

CREATE table UTILISATEURS (
	ID int NOT NULL auto_increment,
	nom varchar(1000),
    email varchar(1000),
    mot_de_passe varchar(1000),
    primary key(ID)
);

INSERT INTO UTILISATEURS(nom, email, mot_de_passe) VALUES
	('Marc','marc.bonsauveur@gmail.com', '123456');

CREATE table OUTILS (
    APPID int NOT NULL auto_increment,
    NOM varchar(1000), 
    OFFRESOIN varchar(1000),	
    SECTEUR ENUM('Médico-social', 'Sanitaire'), 
    SERVICE varchar(1000),
    CIBLE ENUM('Patient', 'Praticien', 'Praticien & Patient'),
    NBCIBLE int(2), 
    DESCR varchar(1000), 
    PRIX varchar(1000), 
    DAT year,
    OS ENUM('Android', 'IOS', 'Android & IOS', 'WEB'),
    SECUR varchar(1000), 
    SOURC varchar(1000), 
    CATEG ENUM('Périnatalité', 'Enfants', 'Adolescents', 'Adultes', 'Personnes Agées', 'Psycho-Oncologie'),
    primary key(APPID)
);

INSERT INTO OUTILS(NOM, OFFRESOIN, SECTEUR, SERVICE, CIBLE, NBCIBLE, DESCR, PRIX, DAT, OS, SECUR, SOURC, CATEG) VALUES
    ('Léa & Léo App','Lien Parent-Enfant','Médico-social ','Handicap','Patient',99,'Léa et Léo est une application réservée aux parents des enfants accueillis en crèches, écoles maternelles, centres de loisirs, périscolaire, séjours découvertes, séjours de vacances, colonies de vacances… ','Gratuite',2022,'Android','Aucune donnée partagée avec des tiers, mais cette appli peut recueillir vos  Informations personnelles, Photos et vidéos, les données sont chiffrées lors de leur transfert et vous pouvez demander la suppression des données','https://play.google.com/store/apps/details?id=com.leaetleo.com&hl=fr&gl=US','Enfants'),
    ('Respire','Cohérence cardiaque','Médico-social ','Handicap','Patient',99,'Respire vous aidera à diminuer votre niveau de stress quotidien en effectuant simplement quelques séances de respiration en pleine conscience. Il suffit de se laisser guider par les mouvements de la forme.','Gratuite',2022,'IOS','Aucune données n est collectées','https://apps.apple.com/us/app/respire/id1453325751','Enfants'),
    ('Relax de BerthX','Cohérence cardiaque','Médico-social ','Handicap','Patient',99,'Inspirez, puis... Expirez ! Rapide, simple et efficace. Utilisez votre respiration pour vous détendre tout en vous faisant guider par des experts de la méditation. Cette application vous permettra de vous détendre en 5 minutes grâce à de simples exercices de respiration.','Gratuite',2020,'IOS','ND','https://apps.apple.com/fr/app/relax-meditation-respiration/id1492874658','Enfants'),
    ('Breaththink ','Cohérence cardiaque','Médico-social ','Handicap','Patient',99,'Imaginez avoir un outil qui peut vous aider à obtenir un soulagement rapide. Un outil toujours à votre disposition et qui vous aide à faire face au stress et à l anxiété.','Achats Intégrés',2021,'Android','Cette appli peut recueillir des informations personnelles, appareil ou autres ID, Les données sont chiffrées lors de leur transfert, Vous pouvez demander la suppression des donnée.','https://play.google.com/store/apps/details?id=one.zest.breathink','Enfants'),
    ('Petit Bambou ','Méditation/Repos','Médico-social ','Handicap','Patient',99,'Apprenez des techniques simples et pratiques aux côtés d instructeurs certifiés et expérimentés. Découvrez et pratiquez la méditation développée par des experts dévoués et reconnus. Vous trouverez des méditations guidées allant de 3 à 20 minutes permettant à chacun, débutant ou expérimenté, de progresser dans sa pratique à son rythme.','Achats Intégrés',2022,'IOS','Les données utilsateur peuvent être utilisées pour vous suivre sur des applications et des sites web appartenant à d autres sociétés, vos données personnelles peuvent être reliées à vous mais pas les les diagnostics de l application','https://apps.apple.com/us/app/petit-bambou-mindfulness/id941222646','Enfants'),
    ('Headspace: Méditation et Repos','Méditation/Repos','Médico-social ','Autisme','Patient',1,'Prenez soin de vous et de votre santé avec Headspace ! Accédez facilement à des centaines de programmes et méditations pour la vie de tous les jours, des relaxations pour dormir, des musiques pour la concentration et des conseils pour prendre soin de votre santé au quotidien.','Achats Intégrés',2022,'Android','Les données utilsateur peuvent être utilisées pour vous suivre sur des applications et des sites web appartenant à d autres sociétés, vos données personnelles peuvent être reliées à vous mais pas les les diagnostics de l application','https://play.google.com/store/apps/details?id=com.getsomeheadspace.android&hl=fr&gl=US','Enfants'),
    ('La Clinique E-santé','Thérapie en ligne (Consulter un psychologue par message texte, audio et video, Thérapie par message)','Sanitaire','Psychiatrie','Praticien & Patient',1,'Avec cette appli, La Clinique E-santé révolutionne votre expérience thérapeutique en vous offrant un suivi sur mesure avec votre psychologue, mais aussi des outils accessibles en un clic, le tout en vous libérant des contraintes d’un suivi en cabinet.','Payante (abonnement par semaine de 38 € à 44 €)',2020,'Android','ND','https://play.google.com/store/apps/details?id=com.lacliniqueesante.android&hl=fr&gl=US&__hstc=103704607.25b8037f2cacbfb85563b4a3ae583ed9.1665994711439.1665994711439.1665994711439.1&__hssc=103704607.1.1665994711440&__hsfp=1586546014&hsCtaTracking=a9505c7a-7293-4301-a5ad-5eb3948c108d%7C2b6b2e97-1f15-49b8-b11f-e100cc351033','Adolescents'),
    ('MentalAPPS','Télésuivi de pathologie, en particulier la dépression','Sanitaire','Psychiatrie','Praticien & Patient',1,'Cette solution aide les psychiatres et médecins généralistes à mieux suivre leurs patients entre deux consultations.','Gratuite',2022,'Android','ND','https://play.google.com/store/apps/details?id=com.mentalapps.terekea&hl=fr&gl=US','Adolescents'),
    ('Stop Blues','Prévention sucide (application et site web)','Médico-social ','Psychiatrie','Patient',1,'Tout le monde peut un jour se sentir seul, fatigué, déprimé, découragé et en souffrir. Mais toute situation a des solutions. StopBlues est un site internet qui permet d accéder rapidement à une panoplie d informations et d outils pour mieux comprendre la situation et trouver des solutions pour soi-même ou pour un proche. Des vidéos informent sur le blues, le mal être et la souffrance, leurs signes, leurs causes, les solutions et les aides et actions possibles. Ceux qui en ont besoin bénéficient de conseils et d’outils pour aller mieux et les accompagner. Une cartographie des ressources existantes dans la ville est également à disposition.','Gratuite',2020,'Android & IOS','ND','https://play.google.com/store/apps/details?id=com.inserm.stopblues','Adolescents'),
    ('Catch it','Lutter contre la dépression','Médico-social ','Addiction','Patient',1,'Catch It est un projet commun entre les universités de Liverpool et de Manchester, pour aider les utilisateurs à mieux comprendre leurs humeurs grâce à l utilisation d un journal en cours. L application a été conçue pour illustrer certains des principes clés des approches psychologiques pour la santé mentale et le bien-être, et spécifiquement thérapie cognitivo-comportementale (TCC).','Gratuite',2020,'Android','ND','https://www.etat-depressif.com/catch-application-depression/','Adolescents'),
    ('Renforcer l estime de soi !','Estime de soi','Médico-social ','Addiction','Patient',1,'Ne serait-il pas merveilleux que la vie te tapote parfois sur l‘épaule et te rappelle, ce qui est vraiment important ? Qu‘elle te rappelle, à quel point tu es admirable ? Oui, tu es admirable ! Et tu ne devrais jamais en douter ! Télécharge notre appli mobile et laisse la vie te saluer chaque jour ! Laisse-toi inspirer, motiver et t‘aider à t‘aimer toi-même ! Avec nos messages quotidiens.','Achats Intégrés',2020,'Android','ND','https://play.google.com/store/apps/details?id=de.ky_o.android&hl=fr&gl=US&pli=1','Adolescents'),
    ('BetterMe : Santé Mentale','Aide à la gestion du stress','Autisme','Médico-social ','Patient',1,'BetterMe: méditation d Aide Personnelle pour les personnes qui ne peuvent pas méditer! Tout ce dont vous avez besoin, c est de quelques minutes par jour pour vous amener à un état de calme et de bien-être, et équilibrer votre vie en utilisant une combinaison de méditations guidées et de techniques. L approche de BetterMe est un ensemble de méthodes de relaxation simples et pratiques pour tous.','Achats Intégrés',2022,'Android & IOS','Aucune donnée partagée avec des tiers, mais cette appli peut recueillir des informations personnelles, informations financières, les données sont chiffrées lors de leur transfert et Vous pouvez demander la suppression des données','https://play.google.com/store/apps/details?id=com.gen.bettermeditation&hl=fr&gl=US','Adolescents'),
    ('RespiRelax +','Cohérence cardiaque','Médico-social ','Handicap','Patient',1,'Depuis sa création en 2012 par les Thermes d’Allevard, l’application RespiRelax+ vous permet de retrouver calme et détente en quelques minutes seulement','Gratuite',2017,'Android','ND','https://play.google.com/store/apps/details?id=com.thermesallevard.respi_relax&hl=fr&gl=US','Adultes'),
    ('Inner Balance','Cohérence cardiaque','Médico-social ','Handicap','Patient',1,'Avec le capteur Inner Balance Bluetooth pour Android et iOS, vous pratiquerez la cohérence cardiaque et améliorerez votre bien-être à travers la formation, l éducation et l’auto-surveillance. Cette application peut aussi bien être utilisée en pratique personnelle et en pratique professionelle. Au niveau personnel, ce support permet de structurer et d’évaluer les progrès d’une pratique quotidienne. Au niveau professionnel, l application permet de démontrer à vos patients/clients la variabilité cardiaque et la cohérence cardiaque grâce au tachogramme et spectrogramme intégré.','Payante (189 €)',NULL,'Android & IOS','ND','https://www.coherenceinfo.com/produit/inner-balance/','Adultes'),
    ('La Clinique E-santé','Thérapie en ligne (Consulter un psychologue par message texte, audio et video, Thérapie par message)','Sanitaire','Psychiatrie','Praticien & Patient',1,'Avec cette appli, La Clinique E-santé révolutionne votre expérience thérapeutique en vous offrant un suivi sur mesure avec votre psychologue, mais aussi des outils accessibles en un clic, le tout en vous libérant des contraintes d’un suivi en cabinet.','Payante (abonnement par semaine de 38 € à 44 €)',2020,'Android','ND','https://play.google.com/store/apps/details?id=com.lacliniqueesante.android&hl=fr&gl=US&__hstc=103704607.25b8037f2cacbfb85563b4a3ae583ed9.1665994711439.1665994711439.1665994711439.1&__hssc=103704607.1.1665994711440&__hsfp=1586546014&hsCtaTracking=a9505c7a-7293-4301-a5ad-5eb3948c108d%7C2b6b2e97-1f15-49b8-b11f-e100cc351033','Adultes'),
    ('MindDoc','Thérapie en ligne  ','Sanitaire','Addiction','Praticien & Patient',1,'Développé par des psychologues cliniciens en étroite collaboration avec des chercheurs de premier plan pour ceux qui veulent en savoir plus sur le bien-être émotionnel ou qui souffrent de maladies mentales légères à modérées, notamment la dépression, l anxiété, l insomnie et les troubles de l alimentation.','Achats Intégrés',2022,'Android & IOS','Cette appli peut recueillir et partager vos informations personnelles, Forme et santé... Ces données sont chiffrées lors de leur transfert et vous pouvez demander leur suppression.','https://minddoc.com/us/en','Adultes'),
    ('SIMPle+','Éducation Thérapeutique','Sanitaire','Psychiatrie','Patient',1,'L application SIMPLe délivre des messages de psychoéducation individualisés, et permet la visualisation de graphiques des modifications de l humeur (agenda de l humeur).','Gratuite',2021,'Android','ND','https://play.google.com/store/apps/details?id=py.com.sodep.simpleplus.prod&pli=1','Adultes'),
    ('Psychiatrie','Veille Pyschiatrie','Sanitaire','Psychiatrie','Praticien',1,'La psychiatrie est la spécialité médicale consacrée au diagnostic, à la prévention et au traitement des troubles mentaux. Ceux-ci incluent diverses mésadaptations liées à l humeur, au comportement, à la cognition et aux perceptions. L’évaluation psychiatrique initiale d’une personne commence généralement par un examen des antécédents médicaux et de l’état mental. Des examens physiques et des tests psychologiques peuvent être effectués.','Gratuite',2022,'Android','Cette appli peut partager ces types de données avec des tiers Position, Informations personnelles, mais aucune donnée collectée','https://play.google.com/store/apps/details?id=psychiatrie.pro&hl=fr&gl=US','Adultes'),
    ('Yoga | Down Dog','Excercice Yoga','Médico-social ','Addiction','Patient',1,'Avec Down Dog, obtenez une séance de yoga différente, à chaque fois que vous vous installez sur votre tapis. Contrairement à des vidéos préenregistrées qui s enchaînent, Down Dog ne vous fera pas répéter le même entraînement encore et encore. Avec plus de 60 000 configurations différentes, Down Dog vous donne le pouvoir de créer une pratique de yoga sur mesure !','Achats Intégrés',2022,'Android','Aucune donnée partagée avec des tiers, mais cette appli peut recueillir vos Informations personnelles, Activité dans l application, les données sont chiffrées lors de leur transfert et vous pouvez demander la suppression des données','https://play.google.com/store/apps/details?id=com.downdogapp&hl=fr&gl=US','Adultes'),
    ('Motivation - Phrases du jour','Motivation','Médico-social ','Addiction','Patient',1,'Que vous traversiez des moments difficiles, que vous ayez besoin d’un coup de pouce pour parvenir à effectuer vos tâches quotidiennes ou que vous aimiez partager des citations inspirantes sur les réseaux sociaux, Motivation est fait pour vous. Les rappels positifs sont l’un des outils les plus simples et les plus efficaces pour la croissance mentale. Ils vous aident à garder des pensées positives à l’esprit dès le début de la journée, afin de pouvoir y recourir facilement les jours difficiles où vous en avez le plus besoin.','Achats Intégrés',2022,'Android & IOS','Aucune donnée partagée avec des tiers, mais cette appli peut recueillir vos Informations personnelles, Activité dans l application, les données sont chiffrées lors de leur transfert et vous pouvez demander la suppression des données','https://play.google.com/store/apps/details?id=com.hrd.motivation&hl=fr&gl=US','Adultes'),
    ('Daylio Journal','Bien être','Médico-social ','Patient','Handicap',1,'Daylio vous permet de tenir un journal privé sans avoir à taper une seule ligne. Essayez dès maintenant GRATUITEMENT cette application de micro-journal magnifiquement conçue et incroyablement simple !','Achats Intégrés',2022,'Android & IOS','Aucune donnée partagée avec des tiers, mais cette appli peut recueillir vos Informations personnelles, Activité dans l application, les données sont chiffrées lors de leur transfert et vous pouvez demander la suppression des données','https://play.google.com/store/apps/details?id=net.daylio&hl=fr&gl=US','Adultes'),
    ('Semio8G','Votre guide pour un entretien clinique précis et détaillé','Sanitaire','Psychiatrie','Praticien',1,'Semio8G peut se définir comme une application web multi supports capable d’accompagner le clinicien et les équipes dans leurs praxis cliniques. En s’appuyant sur les références majeures de la sémiologie psychiatrique, elle offre à l’utilisateur la possibilité de monter en compétence dans sa capacité à observer, organiser, synthétiser, structurer et transmettre sa vision clinique. Semio8G possède en plus une fonction pédagogique et peut aider l’utilisateur à intégrer progressivement son contenu. L’objectif final de Semio8G consiste à améliorer les prises en soin des personnes en souffrance psychique par la montée en compétence des équipes et du professionnel dans le registre de la clinique.','Gratuit',2022,'WEB','ND','https://semio8g.grieps.fr/','Psycho-Oncologie')
;

SELECT * FROM OUTILS;
